homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_loc_home
  longitude: !secret lat_long_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  api_password: !secret hass_pass
  login_attempts_threshold: 3
  ip_ban_enabled: True
  ssl_certificate: !secret http_ssl_sert
  ssl_key: !secret http_ssl_key
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# History Graph
history_graph:
  power:
    name: Power Graph
    entities:
      - sensor.floor_fan_energy
      - sensor.tv_energy
    hours_to_show: 168
    refresh: 60
  wifi_speed:
    name: WiFi Speed
    entities:
      - sensor.fastcom_download
    hours_to_show: 168
    refresh: 60
# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor:
  - platform: yr
  - platform: google_wifi
    name: Google Wifi
  - platform: fastdotcom
    minute:
      - 0
      - 59
  - platform: template
    sensors:
      floor_fan_energy:
        friendly_name: "Floor Fan Usage"
        unit_of_measurement: kWh
        value_template: "{{ states.switch.floor_fan.today_energy_kwh }}"

      tv_energy:
        friendly_name: "TV Power Usage"
        unit_of_measurement: kWh
        value_template: "{{ states.switch.wifi_outlet_2.today_energy_kwh }}"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
device_tracker: !include device_tracker.yaml


# Lutron
lutron_caseta:
    host: !secret lutron_host
    keyfile: !secret caseta_key
    certfile: !secret caseta_crt
    ca_certs: !secret caseta_bridge_crt

# Nest Developers API config
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Etekcity VeSync Voltson Smart Plugs
switch:
  - platform: vesync
    username: !secret vesync_username
    password: !secret vesync_password